[package]
name = "dms-cdc-operator"
version = "0.1.10"
edition = "2021"
license = "MIT"
description = "The dms-cdc-operator is a Rust-based utility for comparing the state of a list of tables in an Amazon RDS database with data stored in Parquet files on Amazon S3, particularly useful for change data capture (CDC) scenarios"
readme = "README.md"
homepage = "https://github.com/nikoshet/rust-dms-cdc-operator"
repository = "https://github.com/nikoshet/rust-dms-cdc-operator"
keywords = ["postgres", "s3", "cdc", "parquet", "polars"]
documentation = "https://docs.rs/dms-cdc-operator"
exclude = ["script.sh"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-s3 = "1.21.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
log = "0.4.21"
sqlx = { version = "0.7.4", features = [
    "postgres",
    "runtime-tokio",
    "tls-rustls",
] }
colored = "2.1.0"
polars = { version = "0.39.2", features = [
    "timezones",
    "json",
    "lazy",
    "aws",
    "parquet",
    "dtype-decimal",
    "streaming",
    "strings",
] }
chrono = "0.4.37"
async-trait = "0.1.79"
rust-pgdatadiff = "0.1.4"
indexmap = { version = "2.2.6", features = ["serde"] }
polars-core = "0.39.2"
rust_decimal = "1.35.0"
tracing = "0.1.40"
deadpool-postgres = "0.13.2"
futures = "0.3.30"
clap = "4.5.4"

[dev-dependencies]
mockall = "0.12.1"

[lib]
test = true
edition = "2021"
crate-type = ["lib"]
name = "dms_cdc_operator"

[workspace]
members = ["dms-cdc-operator-client"]
