[package]
name = "rust-cdc-validator"
version = "0.1.7"
edition = "2021"
license = "MIT"
description = "The rust-cdc-validator is a Rust-based utility for comparing the state of a list of tables in an Amazon RDS database with data stored in Parquet files on Amazon S3, particularly useful for change data capture (CDC) scenarios"
readme = "README.md"
homepage = "https://github.com/nikoshet/rust-cdc-validator"
repository = "https://github.com/nikoshet/rust-cdc-validator"
keywords = ["postgres", "s3", "cdc", "parquet", "polars"]
documentation = "https://docs.rs/rust-cdc-validator"
exclude = ["script.sh"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-s3 = "1.21.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
log = "0.4.21"
bytes = "1.6.0"
sqlx = { version = "0.7.4", features = [
    "postgres",
    "runtime-tokio",
    "tls-native-tls",
] }
colored = "2.1.0"
polars = { version = "0.39.2", features = [
    "timezones",
    "json",
    "lazy",
    "aws",
    "parquet",
    "dtype-decimal",
    "streaming",
    "strings",
] }
chrono = "0.4.37"
serde_json = { version = "1.0.115", features = [
    "preserve_order",
    "arbitrary_precision",
] }
serde = { version = "1.0.189", features = ["derive"] }
async-trait = "0.1.79"
rust-pgdatadiff = "0.1.4"
indexmap = { version = "2.2.6", features = ["serde"] }
polars-core = "0.39.2"
polars-utils = "0.39.2"
rust_decimal = "1.35.0"
tracing = "0.1.40"

[dev-dependencies]
mockall = "0.12.1"

[lib]
test = true
edition = "2021"
crate-type = ["lib"]
name = "rust_cdc_validator"

[workspace]
members = ["rust-cdc-validator-client"]
