[package]
name = "rust-cdc-validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.21.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
env_logger = "0.11.3"
log = "0.4.21"
parquet = "51.0.0"
bytes = "1.6.0"
bytestr = "0.1.0"
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio", "tls-native-tls"] }
clap = { version = "4.5.4", features = ["derive"], optional = true }
colored = "2.1.0"
polars = { version = "0.38.3", features = ["timezones", "json", "lazy", "aws", "parquet", "dtype-decimal", "streaming"]}
chrono = "0.4.37"
serde_json = { version = "1.0.115", features = ["preserve_order", "arbitrary_precision"] }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.79"
rust-pgdatadiff = "0.1.4"
indexmap = { version = "2.2.6", features = ["serde"]}
polars-core = "0.38.3"
polars-utils = "0.38.3"
mockall = "0.12.1"
rust_decimal = "1.35.0"
inquire = { version = "0.7.4", optional = true }

[features]
default = ["with-inquire"]
with-inquire = ["dep:inquire"]
with-clap = ["dep:clap"]
