services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
